# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], default='A', max_length=1),
        ),
    ]
