# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 07:39
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0002_auto_20170727_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
