# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 07:59
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0003_vessel_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voy',
            fields=[
                ('voy', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('performa_in', models.DateTimeField(blank=True, null=True)),
                ('performa_out', models.DateTimeField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True, verbose_name='Arrival Time')),
                ('etb', models.DateTimeField(blank=True, null=True, verbose_name='Berth Time')),
                ('etd', models.DateTimeField(blank=True, null=True, verbose_name='Departure Time')),
                ('dis_no', models.IntegerField(default=0, verbose_name='Number of Discharg')),
                ('load_no', models.IntegerField(default=0, verbose_name='Number of Loading')),
                ('est_teu', models.IntegerField(default=0, verbose_name='Estimate TEU')),
                ('vsl_oper', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vsl Operator')),
                ('arrival_draft', models.CharField(blank=True, max_length=50, null=True, verbose_name='Arrival draft')),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='berth.Service')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='berth.Terminal')),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='service',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='terminal',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='vessel',
        ),
        migrations.AlterField(
            model_name='vessel',
            name='color',
            field=colorfield.fields.ColorField(default='#CCFFFF', max_length=18),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.AddField(
            model_name='voy',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='berth.Vessel'),
        ),
    ]
