# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0004_auto_20170727_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='voy',
            name='start_pos',
            field=models.IntegerField(default=50, verbose_name='Start Position'),
        ),
        migrations.AlterField(
            model_name='voy',
            name='remark',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
