# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0005_auto_20170727_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='voy',
            name='departure_draft',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='Departure draft'),
        ),
        migrations.AlterField(
            model_name='voy',
            name='arrival_draft',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='Arrival draft'),
        ),
        migrations.AlterField(
            model_name='voy',
            name='dis_no',
            field=models.IntegerField(default=0, verbose_name='Number of Discharge'),
        ),
    ]
