# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0006_auto_20170727_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
