# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0007_vessel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='voy',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Saved as Draft'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
