# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0008_auto_20170731_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
