# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0009_auto_20170731_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='voy',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
