# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0010_voy_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='start_range',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Excel start range'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='stop_range',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Excel stop range'),
        ),
    ]
