# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 12:43
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0011_auto_20170731_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=colorfield.fields.ColorField(default='#CCFFFF', max_length=18),
        ),
    ]
