# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 12:53
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0012_service_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='color',
            field=colorfield.fields.ColorField(default='', max_length=18),
        ),
    ]
