# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 08:25
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0013_auto_20170801_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='voy',
            name='move_confirm',
            field=models.BooleanField(default=False, verbose_name='Move Confirm'),
        ),
        migrations.AddField(
            model_name='voy',
            name='move_performa',
            field=models.IntegerField(default=0, verbose_name='Move Performa'),
        ),
        migrations.AddField(
            model_name='voy',
            name='text_pos',
            field=models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('T', 'Top'), ('B', 'Buttom')], default='R', max_length=1, verbose_name='Text position for Barge'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='v_type',
            field=models.CharField(choices=[('VESSEL', 'Vessel'), ('BARGE', 'Barge'), ('NOTICE', 'Notice')], default='VESSEL', max_length=10, verbose_name='Vessel Type'),
        ),
        migrations.AlterField(
            model_name='voy',
            name='dis_no',
            field=models.IntegerField(default=0, verbose_name='Discharge'),
        ),
        migrations.AlterField(
            model_name='voy',
            name='est_teu',
            field=models.IntegerField(default=0, verbose_name='Est TEU'),
        ),
        migrations.AlterField(
            model_name='voy',
            name='eta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETA'),
        ),
        migrations.AlterField(
            model_name='voy',
            name='etb',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETB'),
        ),
        migrations.AlterField(
            model_name='voy',
            name='etd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ETD'),
        ),
        migrations.AlterField(
            model_name='voy',
            name='load_no',
            field=models.IntegerField(default=0, verbose_name='Loading'),
        ),
    ]
