# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berth', '0014_auto_20170802_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='move_performa',
            field=models.IntegerField(default=0, verbose_name='Move Performa'),
        ),
    ]
