# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_container_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='new_bay',
            new_name='original_bay',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='new_stowage',
            new_name='original_stowage',
        ),
    ]
