# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_auto_20180131_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='imdg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='on_deck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='container',
            name='un_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
