# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayplanfile',
            name='ready_to_load',
            field=models.BooleanField(default=False),
        ),
    ]
