# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bayplan', '0002_auto_20171225_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField()),
                ('container', models.CharField(max_length=11)),
                ('iso_code', models.CharField(blank=True, max_length=4, null=True)),
                ('full', models.BooleanField(default=False)),
                ('partner', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.IntegerField()),
                ('load_port', models.CharField(blank=True, max_length=10, null=True)),
                ('dis_port', models.CharField(blank=True, max_length=10, null=True)),
                ('deliverly_port', models.CharField(blank=True, max_length=10, null=True)),
                ('good_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('stowage', models.CharField(max_length=10)),
                ('new_stowage', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('bayPlanfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayplan.BayPlanFile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
