# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayplan', '0003_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayplanfile',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bayplanfile',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
