# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayplan', '0003_auto_20180130_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayplanfile',
            name='updated_filename',
            field=models.FileField(blank=True, null=True, upload_to='bayplan/%Y/%m/%d/'),
        ),
    ]
